### ISSUE TITLE
Переименовать репозиторий согласно Naming convention

### ISSUE THREAD

**Issue by annndruha** [profcomff/aciniformes-project#2]
Это должен быть либо `-tgbot`, либо `-api`, либо скорее оба одновременно.
В вики не прописан Naming convention для репозиториев включающих сразу два предназначения.

**Comment by dyakovri** [comment]
Это API
Но вообще это все еще форк с репозитория в моем личном аккаунте, в котором все еще нет функционала

**Comment by annndruha** [comment]
Не очень понимаю что ты имеешь в виду под отсутствием функционала, бот ведь работает. А редмихи нет

**Comment by annndruha** [comment]
Разобрались
