### ISSUE TITLE
Написать гайд к существующему коду, чтобы было проще разбираться

### ISSUE THREAD

**Issue by grigoriev-semyon** [profcomff/aciniformes-project#4]

**Comment by grigoriev-semyon** [comment]
В общем, архитектура такая: есть три сервиса, они разворачиваются в отдельных контейнерах и общаются между собой по http.
По порядку: 
1) Круд апи: сервис чтоб писать в базу, брать данные и тд. Через него все сервисы общаются с бд. Написано на hibernate подобных интерфейсах, сделано на данный Момент всё.
2) Шедулер: Штука, которая берет данные из первого сервиса и опрашивает нужные адреса с каким-то промежутком времени, потом обратно отдает круд сервису логи. Если вдруг ответ не такой, какой хотел пользователь, шедулер кидает алерт (алерты там это табличка в бд типа кучи фильтров, и написано че делать если вот так сломалось)
Вроде что-то надо доделать, код так себе, тестов почти нет
3) Алерт бот: просто тг бот, который выкидывает алерты по юзер айди кому-то.
Вообще не реализован, надо доделать

@dyakovri @Wudext

**Comment by grigoriev-semyon** [comment]
Это был комментарий от Миши

**Comment by dyakovri** [comment]
Что такое hibernate подобные интерфейсы? (Я правда не знаю, другим ещё сложнее будет) @grigoriev-semyon
